### ISSUE TITLE
Fertilizer Ratios

### ISSUE THREAD

**Issue by skai59** [Thorinair/Stardew-Profits#11]
As seen in the data.js file, when there is fertilizer, it just takes the ratio of the fertilizer and apply it to ratioN, ratioS, ratioG respectively, and it doesn't bother with player level. Is this how it is or am I not seeing something? On the wiki page, there is a whole table for fertilizer crop quality ratios.

**Comment by Thorinair** [comment]
Back when I played, the fertilizers would override the player ratios. I don't know if this changed. If no fertilizer is used, it uses level ratios.
https://github.com/Thorinair/Stardew-Profits/blob/master/js/main.js#L143

**Comment by skai59** [comment]
It has:
https://stardewvalleywiki.com/Fertilizer#Crop_Quality_Ratios

**Comment by Thorinair** [comment]
This has now been fixed!
