### ISSUE TITLE
GitHub Pages (hosting)

### ISSUE THREAD

**Issue by kalisjoshua** [Thorinair/Stardew-Profits#13]
Since this is a static site - nothing server-side necessary - you should turn on the GitHub Pages option so that people can use it without cloning/downloading it. I'd be happy to help if you would like it.

**Comment by Thorinair** [comment]
https://thorinair.github.io/Stardew-Profits/
This option has been active ever since the project's inception.

**Comment by kalisjoshua** [comment]
Awesome! Totally my fault for not even checking; #noob. 

Just as a suggestion then, add the link to the README.md and the top "description" area of the repository landing page.
