### ISSUE TITLE
Suggestion for coffee bean seed price

### ISSUE THREAD

**Issue by Azzinoth224** [Thorinair/Stardew-Profits#19]
I think you shouldn't use the travelling cart price of 2500 for the seeds. In contrast to all other crops, coffee beans can be used as seeds themselfes. Coffe beans only have a value of 15, so you effectively only lose that much money if you use a coffe bean as seed instead of seling it. As coffe beans have a regrow time of 2 days and drop 4 beans, you can very quickly build up a large stock. Currently i alway turn off "pay for seeds" and memorize this value, then i turn it on again to compare it with all other crops. I suggest to to add 15g as "seed price from stock" to the seed price list.

**Comment by frenchiveruti** [comment]
I believe it's quite hard to make a case for this as it's impossible to know if the player will reuse the seeds or process them.

**Comment by Thorinair** [comment]
This is a bit similar to #32, maybe something could be figured out using the changes in that issue discussion.

**Comment by Thorinair** [comment]
There is now a "Process & Replant" option which will use half of the produce to replant it!
