### ISSUE TITLE
Raw tea leaves value wrong

### ISSUE THREAD

**Issue by DeputyChuck** [Thorinair/Stardew-Profits#37]
Tea leaves monetary value is not accurate when viewed as raw 

Value per leaf should be 50, but it's set at 0.75
And when you look at the percentage chance of getting each quality of crops, it shows : (Normal) (0%) instead of (100%) 

Price issue not present when showing Keg or Jar value

![1](https://user-images.githubusercontent.com/72897146/108637931-d5eeae80-745a-11eb-80fa-45589d859ea5.png)

I can't code, just wanted to bring that to your attention.

**Comment by DeputyChuck** [comment]
A little bit more testing : the price seems to be massively adjusted by farming skill level, suggesting that it only takes silver and gold quality possibilities into account to calculate total profit and discards all normal quality values.

In other words, even though silver and gold quality are not possible with tea leaves, Stardew-profit only includes those crops that WOULD be silver or gold in the total profit and calculates the normal quality ones at zero

**Comment by FinalDoom** [comment]
Wow yeah, I don't know why I didn't notice this when I added it. It should only be using normal quality, no silver and gold, as the tooltip shows--but something must have gotten fudged. Should be an easy fix, thanks for pointing this out.
