### ISSUE TITLE
Missing “Bear’s knowledge option”

### ISSUE THREAD

**Issue by reden87** [Thorinair/Stardew-Profits#40]
When the “[Bear’s knowledge](https://stardewvalleywiki.com/Bear%27s_Knowledge)” quest is finished, the blackberry and salmonberry price increases to 3x permanently.

This checkbox is missing from the calculator.

**Comment by Thorinair** [comment]
Blackberries and Salmonberries cannot be grown on the farm and can only be foraged in the natural bushes. As such, they are not part of the crops supported by the calculator to begin with, so no crops would be affected by the bonus. :)
