### ISSUE TITLE
Greenhouse calculations are completely wrong

### ISSUE THREAD

**Issue by dooart** [Thorinair/Stardew-Profits#5]
The bug was introduced by [this line](https://github.com/Thorinair/Stardew-Profits/commit/1468b6715e9cc66551ee4697a73e4b3f248b57f8#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR83).

For example, there's no way you can harvest the Sweet Gem Berry 11 times over 28 days:
![image](https://cloud.githubusercontent.com/assets/371426/23184004/e5795856-f875-11e6-8691-d4dbe298852c.png)

**Comment by dooart** [comment]
What exactly were you trying to fix, btw? If create a new issue explaining what is the problem I'll be glad to fix it. :)

**Comment by Thorinair** [comment]
This is what happens when I don't properly test the code before pushing stuff... The change was to fix the fact that ALL the calculations were wrong. It started counting for everything 1 day too short. The issue you reported should be fixed now!

**Comment by dooart** [comment]
🙌

**Comment by dooart** [comment]
I just figured out that since I started playing Stardew Valley, because of [this post](https://steamcommunity.com/app/413150/discussions/0/357287304429890300/#c357287304432193277) I've been counting days wrong and would stop planting things one day earlier. 💩

Sorry for the bug, thanks for the quick fix. :)
