### ISSUE TITLE
Ancient Fruit is missing data

### ISSUE THREAD

**Issue by alohapili** [Thorinair/Stardew-Profits#51]
Ancient Fruit has 0 for most of the profit data. Please add the data.

![image](https://user-images.githubusercontent.com/4334363/194967298-b00d4ae4-03f3-41f2-84da-40e7789584e2.png)

**Comment by Thorinair** [comment]
There is no missing data and this is indeed the correct behavior. Ancient Fruit takes 28 days to initially grow once planted and as such doesn't fit into any of the seasons alone. Please switch to Greenhouse or enable Cross season to extend the maximum number of days.
