### ISSUE TITLE
Setting for seed maker profit loss

### ISSUE THREAD

**Issue by Gfiti** [Thorinair/Stardew-Profits#56]
Hey, would be nice to have a setting that considers produce "not sold" due to having to make seeds again.

Would make a more useful comparison vs pay for seeds. 

(Wiki says about 51% of harvest would need to be sacrivived, but that sure gets more complicated with crops that can be havested multiple times and/or give multiple items)

**Comment by Thorinair** [comment]
This is similar to issue #32, I think it could be discussed there!
I do want to come up with some solution, so lets make that the main thread for that. :)
