### ISSUE TITLE
Ratios for Farming Level 1 do not add up to 100%

### ISSUE THREAD

**Issue by Berbe** [Thorinair/Stardew-Profits#6]
[97% + 2% + 2% = 101%](https://github.com/Thorinair/Stardew-Profits/blob/master/js/data.js#L27), not 100%.

How did you get/compute those ratios?
The official(?) Wiki provides a [completely different formula for 'Farming Level Multiplier'](http://stardewvalleywiki.com/Crops#Crop_Quality).

**Comment by Thorinair** [comment]
Pushed an update to fix this. I assume that I made a typo as it didn't add up only for level 0. The values are copied from this other tool: http://exnil.github.io/crop_planner/
