### ISSUE TITLE
Ancient Seeds are no longer purchasable

### ISSUE THREAD

**Issue by Eiim** [Thorinair/Stardew-Profits#60]
In SV 1.6.3, Ancient Seeds cannot be purchased. The only way to get them now is from the Ancient Seed item or the seed maker. I'm not sure what the best way to handle this is. If you simply remove the Traveling Cart purchase option from the crops.js file, then they can no longer show up. However, as one of the most profitable crops in the game, I think it's still worth including them somehow.

**Comment by Thorinair** [comment]
I have now fixed this issue in the dev branch which I will be pushing soon. The way how it works now is that both Ancient Fruit and Carrots can be set to 0 value for all 3 purchase locations, and it will just work. The visibility is now kept if the name of the other purchase location (which I have set to "Unpurchasable") is anything other than empty. It is also compatible with the new upcoming ROI calculation feature.
