### ISSUE TITLE
"Artisan" skill is seemingly not used in calculation for profits at all.

### ISSUE THREAD

**Issue by WyattAdams** [Thorinair/Stardew-Profits#77]
![Screenshot 2024-06-14 161514](https://github.com/Thorinair/Stardew-Profits/assets/97478173/b508fc4e-11bd-42e5-931b-a54919b7406a)
(Image without artisan selected)

While looking at profits for strawberry wine, I've noticed that the numbers are entirely unaffected across the board whether or not you have the artisan perk selected, when the numbers should be increased (as far as gross profit anyways) by a direct 40% for all wine/artisan good sales.

![Screenshot 2024-06-14 161524](https://github.com/Thorinair/Stardew-Profits/assets/97478173/b317ae5b-b6e2-4951-bfb0-8e6caa3d17f8)
(Image with artisan selected)

**Comment by doodlebunnyhops** [comment]
submitted fix for review: PR #78

**Comment by Thorinair** [comment]
It is now fixed and released on the public version! Big oops on my part! xD
Thanks @doodlebunnyhops for quickly submitting a PR for the fix! :)

**Comment by doodlebunnyhops** [comment]
😅 my whoopsie too - I hadn't did a check after the big dehydrator work but glad to help!
